### PR TITLE
[EndDateTextBox]: Closes #209 Added View text box for Task ending dat…

### LINKED ISSUE #209: View text box for Task ending date picked
I can see the date picked shown on a text box provided

### PR DESCRIPTION
**Pull request by Austinet**

### CODE REVIEW

**Review by a11rew — CHANGES_REQUESTED** [review]
Your tests are failing. Fix it.

**Comment by Austinet** [comment]
> Your tests are failing. Fix it.

I have fixed it, thanks for the review.

**Review by a11rew — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/87580113/132094949-7a3ec3e7-2899-48f7-9370-f9858d042558.mp4

What is this? Your component is supposed to show date selected from a date picker and is also a text box so people can type dates directly.

Update it to show date values and format strings passed into the input so the appear as dates. Possibly, allow for only numeric date values so formatting is easier

**Comment by a11rew** [comment]
Request a review when you're done

**Comment by a11rew** [comment]
This has been implemented.

**Pull request closed without merging**
