### PR TITLE
[timer-text-input]: #222 Add timer text input

### PR DESCRIPTION
**Pull request by demiladeore**
I added the input field and added the 12 hours divide (AM PM) select option

### CODE REVIEW

**Comment by a11rew** [comment]
You're failing the checks. Update your code and run `yarn test` to test before committing.

**Review by a11rew — CHANGES_REQUESTED** [review]
You're failing the checks. Update your code and run yarn test to test before committing.

**Review by a11rew — CHANGES_REQUESTED** [review]
Your input is supposed to take time from the user.\
Why am I able to type letters into it?\
 Update the <input /> and make sure when the user is inputting time the colon that separates hour and minutes shows.

**Review by a11rew — CHANGES_REQUESTED** [review]
- Stop changing App.jsx and any other files outside the newDeadline folder. You can edit the app.jsx file to show your component when testing but don't commit those changes.
- Your component just doesn't work.
When I click on PM or AM it does not update the input box.
When you choose a time, it does not update the box either.
When you try to type the time value that does not update the time value in the box either.
- All these should work before you submit again. If you can't implement the functionality yourself consider using external packages. But make sure your time input box looks exactly like the design

**Comment by demiladeore** [comment]
Hello Glago,
What external package will you recommend cos right now, I'm lost.

**Comment by a11rew** [comment]
Implemented already.

**Pull request closed without merging**
