### PR TITLE
Cancel button

### PR DESCRIPTION
**Pull request by spykelionel**
#218

### CODE REVIEW

**Review by a11rew — CHANGES_REQUESTED** [review]
Looks good. A few things however;
- The rounding you gave the button is larger than specified in the design. Refer to the buttons in the [design system](https://www.figma.com/file/t7TK0AdgKRGqcJCFeq5Fiv/Team-Darwin-Mock-Up-Submission?node-id=115%3A2119) for corner radius values.
- Spread props so your button can be passed stuff like onClick

**Review by a11rew — CHANGES_REQUESTED** [review]
There's literally no red cancel button in the design. 
The cancel button in the design is a gray background circle component with a cross in it. Update your component.

**Review by a11rew — CHANGES_REQUESTED** [review]
X isn't a cross.

Ask your group lead for the design you should be using.

**Comment by a11rew** [comment]
Request review when your tests pass

**Comment by a11rew** [comment]
The component you're building has been implemented already, refer here. https://github.com/zurichat/zc_plugin_reminder/pull/322

**Comment by spykelionel** [comment]
OK . am I supposed to do another task? before approved?

**Pull request closed without merging**
