### PR TITLE
[Deadline text]: Fixes #246 View Deadline Text

### LINKED ISSUE #246: View Deadline Text
As a user, I should be able to see the text, `deadline` on the top left corner of the application board

### PR DESCRIPTION
**Pull request by meenarh**

### CODE REVIEW

**Review by a11rew — CHANGES_REQUESTED** [review]
- You're supposed to build a text container. You don't define the text so don't hardcode it. Update your component to show text passed as children to the component or passed as props.
- Your deadlineText component is supposed to be in the folder of the section using it. Ask your group lead where to put it.
- You don't need to import './index.css' to get styling.
- Components are to be named using PascalCase. i.e. 'DEADLINETEXT' is supposed to be 'DeadlineText'. Read the Readme.

**Comment by a11rew** [comment]
The issue you say your PR fixes does not exist. Check and update.

**Review by a11rew — CHANGES_REQUESTED** [review]
- React rule number 1 in the guidelines is to only use functional components. Read the README
- You're not supposed to be editing `layout/nav`. You're making a simple deadline text component for the deadline list. Ask your group lead where your component should live.
- You're supposed to make your component reusable. I still don't see you using the props here

**Review by a11rew — CHANGES_REQUESTED** [review]
Why are you now returning a button? You're to write a component that displays text under the deadline title. Just take your text as a prop, style it and return it in a `<p/>` tag

**Review by jutivia — CHANGES_REQUESTED** [review]
Task has been done already.

**Pull request closed without merging**
