### PR TITLE
Closes #194 View Text Input for the Assignee

### LINKED ISSUE #194: View text input for the Assignee
I can see a text input to write the name(s) of the assignee

### PR DESCRIPTION
**Pull request by olatunbosun-iyare**
I created a view text input for the Assignee which closes #194

### CODE REVIEW

**Review by olatunbosun-iyare — COMMENTED** [review]
Kindly approve pull request for #194

**Review by a11rew — CHANGES_REQUESTED** [review]
The component is supposed to show a drop down when typing updating with suggestions of assignees. Liaise with your team if you're not the only one to build the whole component. I'll merge when a full component is submitted.

**Comment by olatunbosun-iyare** [comment]
I have made the changes to include a placeholder for the drop down menu, kindly review

**Review by a11rew — APPROVED** [review]
Looks good

**Pull request merged**
