### PR TITLE
[DueDatePicker]: Fixes #207 Add due date picker

### LINKED ISSUE #207: A date picker for Task ending date
As a user, I can see an icon to click to pick a date for the task to end.

### PR DESCRIPTION
**Pull request by literallymarvellous**
# This PR closes #207

### CODE REVIEW

**Review by a11rew — CHANGES_REQUESTED** [review]
- Don't use absolute css units. Pixel values are not responsive. Use percentages instead. 

Everything looks good apart from that 👍. Update the CSS and resubmit

**Comment by a11rew** [comment]
This will be closed. Reopen when you resubmit.

**Comment by literallymarvellous** [comment]
I've made the container-div width responsive but asides from that the remaining absolute units are for padding & margins and I can't make those responsive since their values are very small.

**Comment by a11rew** [comment]
Use % eitherway. 0.1% is valid css

**Pull request closed without merging**
