### PR TITLE
#203 Display Avatar of users assigned to a task

### PR DESCRIPTION
**Pull request by odaisaac**
#### #203 Display Avatar of users assigned to a task.

### CODE REVIEW

**Review by a11rew — CHANGES_REQUESTED** [review]
- Don't commit your .vscode folder.
- I don't see why you're adding `@types/react` in frontend and tailwind to the root repo.
- If you have issues report to your group lead or ask in the slack/whatsapp channels. Don't add packages without good reason.
- Use relative CSS units.
- Use PascalCase for file names in `/frontend`
- Use the assets provided by the designers in the Figma file as well as the colors they use.
- Don't leave `alt` props empty.
- Use ES6 arrow functions for function declarations.
- Read the README!!! (Both frontend and root)

**Comment by a11rew** [comment]
Closing this. Reopen when you update.

**Comment by odaisaac** [comment]
Sorry for the additional package's I don't get it well at  first when I ask
about it before I go ahead to add those, am beginner at React my bad 😇 and
regards the figma assets it's not provided so there is not way I can get
those avatars used in the design I ask for it at morning but am instructed
to find online to put there first

**Comment by a11rew** [comment]
Annotation 2021-09-02 183930 (2)

Find the assets here.

**Comment by odaisaac** [comment]
Ok I will check it out

**Comment by a11rew** [comment]
You're still commiting your .vscode folder, you're still editing the eslint config and you still have package.json conflicts

**Comment by odaisaac** [comment]
Resent in new pull request 😇 and abide with all the rules

**Comment by a11rew** [comment]
You've made changes with merge conflicts, ignored the conflicts and created more commits now your whole fork is messed up with conflicts.\
I can't even get your work to build\ 
Save your work somewhere, read this [article on contributing with git](https://www.dataschool.io/how-to-contribute-on-github/) and open a new pull request with your changes.

**Comment by odaisaac** [comment]
That's what I said I already solved it and opened a new pull request

**Comment by odaisaac** [comment]
https://github.com/zurichat/zc_plugin_reminder/pull/323


Here is the pull link of the new branch

**Pull request closed without merging**
